# A first look at a neural network

## Loading the MNIST dataset from Keras

In [ ]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## The network architecture

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

## The compilation step

In [ ]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

## Preparing the image data

In [ ]:
train_images = train_images.reshape((60000, 28*28))
# train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28*28))
# test_images = test_images.astype("float32") / 255

## "Fitting" the model

In [ ]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0288 - accuracy: 0.9915
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0219 - accuracy: 0.9937
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0169 - accuracy: 0.9952
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0127 - accuracy: 0.9967
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0097 - accuracy: 0.9975


## Using the model to make predictions

In [ ]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 87ms/step


array([2.0934765e-10, 1.1124850e-12, 6.1899549e-08, 1.2141353e-06,
       2.7302590e-16, 2.3643845e-12, 8.8179243e-16, 9.9999869e-01,
       4.6906944e-11, 2.9726519e-09], dtype=float32)

In [ ]:
predictions[0].argmax()

7

In [ ]:
predictions[0][7]

0.9999987

In [ ]:
test_labels[0]

7

## Evaluating the model on new data

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 2s 6ms/step - loss: 0.0757 - accuracy: 0.9789
test_acc: 0.9789000153541565
