TensorFlow APIs

#Constant tensors and variables

##All-ones or all-zeros tensors

In [35]:
import tensorflow as tf 

x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [36]:
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


##Random tensors

In [37]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[-1.3920093 ]
 [-0.60133964]
 [-1.0839808 ]], shape=(3, 1), dtype=float32)


In [38]:
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.6143336 ]
 [0.04216373]
 [0.7127329 ]], shape=(3, 1), dtype=float32)


##NumPy arrays are assignable, but TF tensors are not assignable

In [39]:
import numpy as np 

x = np.ones(shape=(2, 2))
x[0, 0] = 0.
print(x)

[[0. 1.]
 [1. 1.]]


In [41]:
x = tf.ones(shape=(2, 2))
x[0, 0] = 0.
print(x)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

##Creating a TensorFlow variable
tf.Variable is the class meant to manage modifiable state in TensorFlow

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.18344991],
       [-0.4449077 ],
       [ 0.41695228]], dtype=float32)>


##Assigning a value to TF variable

In [34]:
v.assign(tf.ones((3, 1)))

NameError: name 'v' is not defined

In [ ]:
# v.assign(tf.ones((4, 1)))

ValueError: ignored

##Assigning a value to a subset of a TF variable

In [33]:
v[0, 0].assign(3.)

NameError: name 'v' is not defined

##Using `assign_add()`

In [ ]:
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

#Tensor operations: Doing math in TensorFlow

In [ ]:
a = tf.ones((2, 2)) * 2
print(a)

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)


In [ ]:
b = tf.square(a)
print(b)

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
c = tf.sqrt(a)
print(c)

tf.Tensor(
[[1.4142135 1.4142135]
 [1.4142135 1.4142135]], shape=(2, 2), dtype=float32)


In [ ]:
d = b + c 
print(d)

tf.Tensor(
[[5.4142137 5.4142137]
 [5.4142137 5.4142137]], shape=(2, 2), dtype=float32)


In [ ]:
e = tf.matmul(a, b)
print(e)

tf.Tensor(
[[16. 16.]
 [16. 16.]], shape=(2, 2), dtype=float32)


In [45]:
e *= d 
print(e)

NameError: name 'e' is not defined

#GradientTape API
Here’s something NumPy can’t do: retrieve the gradient of any differentiable expression with respect to any of its inputs.

##Using the GradientTape

In [47]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
  result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


##Using GradientTape with constant tensor inputs

In [48]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print(gradient)

tf.Tensor(6.0, shape=(), dtype=float32)


##Using nested gradient tapes to compute second-order gradients

In [52]:
time = tf.Variable(2.)
x=time
with tf.GradientTape() as one_more_tape:
  with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as innter_tape:
      position = 3*x**3+2*x**2+x+1
    speed = innter_tape.gradient(position, time)
  accelaration = outer_tape.gradient(speed, time)
change = one_more_tape.gradient(accelaration, time)
print(speed)
print(accelaration)
print(change)

tf.Tensor(45.0, shape=(), dtype=float32)
tf.Tensor(40.0, shape=(), dtype=float32)
tf.Tensor(18.0, shape=(), dtype=float32)
